apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-proxy
  labels:
    app: binance-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: binance-proxy
  template:
    metadata:
      labels:
        app: binance-proxy
    spec:
      containers:
      - name: binance-proxy
        image: nightshift2k/binance-proxy:latest
        ports:
        - containerPort: 8090
          name: spot
        - containerPort: 8091
          name: futures
        - containerPort: 8092
          name: metrics
        env:
        - name: BPX_LOG_LEVEL
          value: "info"
        - name: BPX_LOG_FORMAT
          value: "json"
        - name: BPX_FEAT_ENABLE_METRICS
          value: "true"
        - name: BPX_RECOVERY_ENABLED
          value: "true"
        - name: BPX_RECOVERY_ERROR_THRESHOLD
          value: "10"
        - name: BPX_RECOVERY_ERROR_WINDOW
          value: "5m"
        
        # Kubernetes will restart container on failure
        restartPolicy: Always
        
        # Enhanced health checks for faster detection
        livenessProbe:
          httpGet:
            path: /live
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8092
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        
        # Startup probe for slow-starting containers
        startupProbe:
          httpGet:
            path: /health
            port: 8092
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6  # 60 seconds total
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
# Horizontal Pod Autoscaler for load-based scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: binance-proxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: binance-proxy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60

---
# Pod Disruption Budget to maintain availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: binance-proxy-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: binance-proxy
