name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint
        run: make lint
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Bin
        uses: actions/upload-artifact@v4
        with:
          name: binance-proxy
          path: ./bin/binance-proxy

### Tests not yet integrated ...
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.24'

  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     - name: Test
  #       run: make cover

  #     - name: Cover
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: cover
  #         path: ./cover.html